[2024-02-15 21:13:36,399 : INFO : main Welcome to our custom log]
[2024-02-15 23:03:33,603 : INFO : main : Welcome to our custom log]
[2024-02-16 15:58:30,215 : INFO : main : Welcome to our custom log]
[2024-02-17 23:59:46,808 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-18 00:00:22,575 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-18 00:04:13,181 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-18 00:04:29,655 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-18 00:04:41,255 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-18 00:05:01,338 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-18 00:10:51,341 : INFO : main : Welcome to our custom log]
[2024-02-18 00:42:03,355 : INFO : main : >>>>> Stage Data ingestion stage started <<<<<<<]
[2024-02-18 00:42:03,359 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-18 00:42:03,360 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-18 00:42:03,360 : INFO : common : created directory at : artifacts]
[2024-02-18 00:42:03,362 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-18 00:42:03,363 : INFO : data_ingestion : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-18 00:51:48,890 : INFO : data_ingestion : Downloaded data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-18 00:51:57,403 : INFO : main : >>>>>> Stage Data ingestion stage completed <<<<<<

x===========x]
[2024-02-18 18:39:34,512 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-18 18:39:34,542 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-18 18:39:34,546 : INFO : common : created directory at : artifacts]
[2024-02-18 18:39:34,546 : INFO : common : created directory at : artifacts/prepare_base_model]
[2024-02-18 18:39:53,341 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-18 18:42:46,878 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-18 18:42:46,880 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-18 18:42:46,884 : INFO : common : created directory at : artifacts]
[2024-02-18 18:42:46,884 : INFO : common : created directory at : artifacts/prepare_base_model]
[2024-02-18 18:42:47,279 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-18 18:44:20,361 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-18 18:44:20,365 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-18 18:44:20,369 : INFO : common : created directory at : artifacts]
[2024-02-18 18:44:20,369 : INFO : common : created directory at : artifacts/prepare_base_model]
[2024-02-18 18:44:20,839 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-18 22:55:18,985 : INFO : main : >>>>> Stage Data ingestion stage started <<<<<<<]
[2024-02-18 22:55:18,988 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-18 22:55:18,990 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-18 22:55:18,990 : INFO : common : created directory at : artifacts]
[2024-02-18 22:55:18,991 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-18 22:55:18,992 : INFO : data_ingestion : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-18 22:59:38,393 : INFO : data_ingestion : Downloaded data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-18 22:59:46,916 : INFO : main : >>>>>> Stage Data ingestion stage completed <<<<<<

x===========x]
[2024-02-18 22:59:46,917 : INFO : main : ******************]
[2024-02-18 22:59:46,918 : INFO : main : >>>>>>>>> Stage Prepare Base Model started <<<<<<<<<<<]
[2024-02-18 22:59:46,919 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-18 22:59:46,921 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-18 22:59:46,922 : INFO : common : created directory at : artifacts]
[2024-02-18 22:59:46,923 : INFO : common : created directory at : artifacts/prepare_base_model]
[2024-02-18 22:59:47,480 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-18 22:59:47,807 : INFO : main : >>>>>>>>>> Stage Prepare Base Model completed <<<<<<<<<<<<

 x=============================x]
[2024-02-19 16:21:26,535 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-19 16:21:26,553 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-19 16:21:26,557 : INFO : common : created directory at : artifacts]
[2024-02-19 16:21:26,558 : INFO : common : created directory at : artifacts/training]
[2024-02-19 17:04:19,415 : INFO : main : >>>>> Stage Data ingestion stage started <<<<<<<]
[2024-02-19 17:04:19,418 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-19 17:04:19,426 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-19 17:04:19,426 : INFO : common : created directory at : artifacts]
[2024-02-19 17:04:19,426 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-19 17:04:19,431 : INFO : data_ingestion : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-19 17:08:40,821 : INFO : data_ingestion : Downloaded data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-19 17:08:52,863 : INFO : main : >>>>>> Stage Data ingestion stage completed <<<<<<

x========================================x]
[2024-02-19 17:08:52,865 : INFO : main : ******************]
[2024-02-19 17:08:52,865 : INFO : main : >>>>>>>>> Stage Prepare Base Model started <<<<<<<<<<<]
[2024-02-19 17:08:52,865 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-19 17:08:52,869 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-19 17:08:52,869 : INFO : common : created directory at : artifacts]
[2024-02-19 17:08:52,869 : INFO : common : created directory at : artifacts/prepare_base_model]
[2024-02-19 17:08:53,494 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-19 17:08:53,865 : INFO : main : >>>>>>>>>> Stage Prepare Base Model completed <<<<<<<<<<<<

 x=============================x]
[2024-02-19 17:08:53,865 : INFO : main : **********************]
[2024-02-19 17:08:53,865 : INFO : main : >>>>>>>>>>>> Stage Training started <<<<<<<<<<<<<<<]
[2024-02-19 17:08:53,869 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-19 17:08:53,873 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-19 17:08:53,873 : INFO : common : created directory at : artifacts]
[2024-02-19 17:08:53,873 : INFO : common : created directory at : artifacts/training]
[2024-02-19 21:59:26,523 : INFO : main : >>>>>>>>>>>>>>>> Stage Training completed <<<<<<<<<<<<<<<<

x====================x]
[2024-02-20 15:36:36,793 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-20 15:36:36,800 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-20 15:36:36,801 : INFO : common : created directory at : artifacts]
[2024-02-20 15:41:39,068 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-20 15:41:39,073 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-20 15:41:39,076 : INFO : common : created directory at : artifacts]
[2024-02-20 15:47:12,831 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-20 15:47:12,839 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-20 15:47:12,841 : INFO : common : created directory at : artifacts]
[2024-02-20 15:57:19,091 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-20 15:57:19,097 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-20 15:57:19,100 : INFO : common : created directory at : artifacts]
[2024-02-20 16:00:40,738 : INFO : common : json file saved at : scores.json]
[2024-02-20 16:00:44,235 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-20 16:00:45,343 : INFO : builder_impl : Assets written to: C:\Users\Savi\AppData\Local\Temp\tmpknl_h9w6\model\data\model\assets]
[2024-02-20 16:07:43,812 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-20 16:07:43,824 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-20 16:07:43,827 : INFO : common : created directory at : artifacts]
[2024-02-20 16:11:08,089 : INFO : common : json file saved at : scores.json]
[2024-02-20 16:11:11,473 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-20 16:11:12,213 : INFO : builder_impl : Assets written to: C:\Users\Savi\AppData\Local\Temp\tmp674y0esv\model\data\model\assets]
[2024-02-20 16:14:00,560 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-20 16:14:00,572 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-20 16:14:00,575 : INFO : common : created directory at : artifacts]
[2024-02-20 16:17:27,540 : INFO : common : json file saved at : scores.json]
[2024-02-20 16:17:31,619 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-20 16:17:32,886 : INFO : builder_impl : Assets written to: C:\Users\Savi\AppData\Local\Temp\tmp8y5w3o2t\model\data\model\assets]
[2024-02-20 16:53:00,967 : INFO : main : >>>>> Stage Data ingestion stage started <<<<<<<]
[2024-02-20 16:53:00,969 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-20 16:53:00,971 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-20 16:53:00,975 : INFO : common : created directory at : artifacts]
[2024-02-20 16:53:00,975 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-20 16:53:00,977 : INFO : data_ingestion : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-20 16:57:44,408 : INFO : data_ingestion : Downloaded data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-20 16:57:53,511 : INFO : main : >>>>>> Stage Data ingestion stage completed <<<<<<

x========================================x]
[2024-02-20 16:57:53,511 : INFO : main : ******************]
[2024-02-20 16:57:53,512 : INFO : main : >>>>>>>>> Stage Prepare Base Model started <<<<<<<<<<<]
[2024-02-20 16:57:53,514 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-20 16:57:53,516 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-20 16:57:53,516 : INFO : common : created directory at : artifacts]
[2024-02-20 16:57:53,517 : INFO : common : created directory at : artifacts/prepare_base_model]
[2024-02-20 16:57:54,022 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-20 16:57:54,236 : INFO : main : >>>>>>>>>> Stage Prepare Base Model completed <<<<<<<<<<<<

 x=============================x]
[2024-02-20 16:57:54,237 : INFO : main : **********************]
[2024-02-20 16:57:54,237 : INFO : main : >>>>>>>>>>>> Stage Training started <<<<<<<<<<<<<<<]
[2024-02-20 16:57:54,239 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-20 16:57:54,241 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-20 16:57:54,242 : INFO : common : created directory at : artifacts]
[2024-02-20 16:57:54,243 : INFO : common : created directory at : artifacts/training]
[2024-02-20 17:59:58,153 : INFO : main : >>>>>>>>>>>>>>>> Stage Training completed <<<<<<<<<<<<<<<<

x====================x]
[2024-02-20 17:59:58,154 : INFO : main : ******************]
[2024-02-20 17:59:58,154 : INFO : main : >>>>>>>>>>>>>>>>> Stage Evaluation Stage started <<<<<<<<<<<<<<<<<<<]
[2024-02-20 17:59:58,157 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-20 17:59:58,158 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-20 17:59:58,159 : INFO : common : created directory at : artifacts]
[2024-02-20 18:01:48,868 : INFO : common : json file saved at : scores.json]
[2024-02-20 18:01:50,228 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-20 18:01:50,904 : INFO : builder_impl : Assets written to: C:\Users\Savi\AppData\Local\Temp\tmpfee0v0me\model\data\model\assets]
[2024-02-20 18:01:57,128 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\8d192d0f0e0247e3a64b27cb2cdf57d0\artifacts\model\data]
[2024-02-20 18:01:57,130 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\8d192d0f0e0247e3a64b27cb2cdf57d0\artifacts\model\data\model]
[2024-02-20 18:01:57,132 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\8d192d0f0e0247e3a64b27cb2cdf57d0\artifacts\model\data\model\assets]
[2024-02-20 18:01:57,137 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\8d192d0f0e0247e3a64b27cb2cdf57d0\artifacts\model\data\model\variables]
[2024-02-20 18:01:57,238 : INFO : main : >>>>>>>>>>>>>> Stage Evaluation Stage completed <<<<<<<<<<<

x========================x]
[2024-02-21 00:26:37,191 : INFO : main : >>>>> Stage Data ingestion stage started <<<<<<<]
[2024-02-21 00:26:37,198 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-21 00:26:37,204 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-21 00:26:37,204 : INFO : common : created directory at : artifacts]
[2024-02-21 00:26:37,205 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-21 00:26:37,205 : INFO : data_ingestion : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-21 00:27:47,059 : INFO : main : >>>>> Stage Data ingestion stage started <<<<<<<]
[2024-02-21 00:27:47,061 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-21 00:27:47,062 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-21 00:27:47,062 : INFO : common : created directory at : artifacts]
[2024-02-21 00:27:47,064 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-21 00:27:47,065 : INFO : data_ingestion : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-21 00:32:02,380 : INFO : data_ingestion : Downloaded data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-21 00:32:12,209 : INFO : main : >>>>>> Stage Data ingestion stage completed <<<<<<

x========================================x]
[2024-02-21 00:32:12,209 : INFO : main : ******************]
[2024-02-21 00:32:12,209 : INFO : main : >>>>>>>>> Stage Prepare Base Model started <<<<<<<<<<<]
[2024-02-21 00:32:12,212 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-21 00:32:12,213 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-21 00:32:12,215 : INFO : common : created directory at : artifacts]
[2024-02-21 00:32:12,215 : INFO : common : created directory at : artifacts/prepare_base_model]
[2024-02-21 00:32:12,874 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-21 00:32:13,155 : INFO : main : >>>>>>>>>> Stage Prepare Base Model completed <<<<<<<<<<<<

 x=============================x]
[2024-02-21 00:32:13,157 : INFO : main : **********************]
[2024-02-21 00:32:13,157 : INFO : main : >>>>>>>>>>>> Stage Training started <<<<<<<<<<<<<<<]
[2024-02-21 00:32:13,159 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-21 00:32:13,160 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-21 00:32:13,161 : INFO : common : created directory at : artifacts]
[2024-02-21 00:32:13,162 : INFO : common : created directory at : artifacts/training]
[2024-02-21 00:38:46,112 : INFO : main : >>>>>>>>>>>>>>>> Stage Training completed <<<<<<<<<<<<<<<<

x====================x]
[2024-02-21 00:38:46,113 : INFO : main : ******************]
[2024-02-21 00:38:46,113 : INFO : main : >>>>>>>>>>>>>>>>> Stage Evaluation Stage started <<<<<<<<<<<<<<<<<<<]
[2024-02-21 00:38:46,115 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-21 00:38:46,116 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-21 00:38:46,117 : INFO : common : created directory at : artifacts]
[2024-02-21 00:40:40,620 : INFO : common : json file saved at : scores.json]
[2024-02-21 00:40:41,956 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-21 00:40:42,556 : INFO : builder_impl : Assets written to: C:\Users\Savi\AppData\Local\Temp\tmpa5ycxrfz\model\data\model\assets]
[2024-02-21 00:40:51,101 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\dd749d0622864361a593982ccf5f1391\artifacts\model\data]
[2024-02-21 00:40:51,104 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\dd749d0622864361a593982ccf5f1391\artifacts\model\data\model]
[2024-02-21 00:40:51,106 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\dd749d0622864361a593982ccf5f1391\artifacts\model\data\model\assets]
[2024-02-21 00:40:51,111 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\dd749d0622864361a593982ccf5f1391\artifacts\model\data\model\variables]
[2024-02-21 00:40:51,229 : INFO : main : >>>>>>>>>>>>>> Stage Evaluation Stage completed <<<<<<<<<<<

x========================x]
[2024-02-21 00:54:47,716 : INFO : main : >>>>> Stage Data ingestion stage started <<<<<<<]
[2024-02-21 00:54:47,719 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-21 00:54:47,721 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-21 00:54:47,722 : INFO : common : created directory at : artifacts]
[2024-02-21 00:54:47,723 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-21 00:54:47,724 : INFO : data_ingestion : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-21 00:59:17,728 : INFO : data_ingestion : Downloaded data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-21 00:59:26,583 : INFO : main : >>>>>> Stage Data ingestion stage completed <<<<<<

x========================================x]
[2024-02-21 00:59:26,583 : INFO : main : ******************]
[2024-02-21 00:59:26,584 : INFO : main : >>>>>>>>> Stage Prepare Base Model started <<<<<<<<<<<]
[2024-02-21 00:59:26,586 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-21 00:59:26,587 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-21 00:59:26,587 : INFO : common : created directory at : artifacts]
[2024-02-21 00:59:26,588 : INFO : common : created directory at : artifacts/prepare_base_model]
[2024-02-21 00:59:27,030 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-21 00:59:27,356 : INFO : main : >>>>>>>>>> Stage Prepare Base Model completed <<<<<<<<<<<<

 x=============================x]
[2024-02-21 00:59:27,358 : INFO : main : **********************]
[2024-02-21 00:59:27,359 : INFO : main : >>>>>>>>>>>> Stage Training started <<<<<<<<<<<<<<<]
[2024-02-21 00:59:27,362 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-21 00:59:27,364 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-21 00:59:27,365 : INFO : common : created directory at : artifacts]
[2024-02-21 00:59:27,366 : INFO : common : created directory at : artifacts/training]
[2024-02-21 01:06:11,543 : INFO : main : >>>>>>>>>>>>>>>> Stage Training completed <<<<<<<<<<<<<<<<

x====================x]
[2024-02-21 01:06:11,543 : INFO : main : ******************]
[2024-02-21 01:06:11,544 : INFO : main : >>>>>>>>>>>>>>>>> Stage Evaluation Stage started <<<<<<<<<<<<<<<<<<<]
[2024-02-21 01:06:11,545 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-21 01:06:11,547 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-21 01:06:11,547 : INFO : common : created directory at : artifacts]
[2024-02-21 01:08:09,258 : INFO : common : json file saved at : scores.json]
[2024-02-21 01:08:10,531 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-21 01:08:11,161 : INFO : builder_impl : Assets written to: C:\Users\Savi\AppData\Local\Temp\tmpmeqvpztv\model\data\model\assets]
[2024-02-21 01:08:17,023 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\8912758be0a8441f90fbe4f25ba59f95\artifacts\model\data]
[2024-02-21 01:08:17,026 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\8912758be0a8441f90fbe4f25ba59f95\artifacts\model\data\model]
[2024-02-21 01:08:17,028 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\8912758be0a8441f90fbe4f25ba59f95\artifacts\model\data\model\assets]
[2024-02-21 01:08:17,034 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\8912758be0a8441f90fbe4f25ba59f95\artifacts\model\data\model\variables]
[2024-02-21 01:08:17,139 : INFO : main : >>>>>>>>>>>>>> Stage Evaluation Stage completed <<<<<<<<<<<

x========================x]
[2024-02-21 01:16:19,323 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-21 01:16:19,327 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-21 01:16:19,329 : INFO : common : created directory at : artifacts]
[2024-02-21 01:18:17,346 : INFO : common : json file saved at : scores.json]
[2024-02-21 01:18:20,486 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-21 01:18:21,244 : INFO : builder_impl : Assets written to: C:\Users\Savi\AppData\Local\Temp\tmpp3cnawoq\model\data\model\assets]
[2024-02-21 01:51:49,177 : INFO : main : >>>>> Stage Data ingestion stage started <<<<<<<]
[2024-02-21 01:51:49,181 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-21 01:51:49,181 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-21 01:51:49,185 : INFO : common : created directory at : artifacts]
[2024-02-21 01:51:49,185 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-21 01:51:49,185 : INFO : data_ingestion : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-21 01:56:19,587 : INFO : data_ingestion : Downloaded data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-21 01:56:35,729 : INFO : main : >>>>>> Stage Data ingestion stage completed <<<<<<

x========================================x]
[2024-02-21 01:56:35,729 : INFO : main : ******************]
[2024-02-21 01:56:35,729 : INFO : main : >>>>>>>>> Stage Prepare Base Model started <<<<<<<<<<<]
[2024-02-21 01:56:35,729 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-21 01:56:35,733 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-21 01:56:35,733 : INFO : common : created directory at : artifacts]
[2024-02-21 01:56:35,737 : INFO : common : created directory at : artifacts/prepare_base_model]
[2024-02-21 01:56:36,398 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-21 01:56:37,014 : INFO : main : >>>>>>>>>> Stage Prepare Base Model completed <<<<<<<<<<<<

 x=============================x]
[2024-02-21 01:56:37,014 : INFO : main : **********************]
[2024-02-21 01:56:37,014 : INFO : main : >>>>>>>>>>>> Stage Training started <<<<<<<<<<<<<<<]
[2024-02-21 01:56:37,018 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-21 01:56:37,022 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-21 01:56:37,022 : INFO : common : created directory at : artifacts]
[2024-02-21 01:56:37,022 : INFO : common : created directory at : artifacts/training]
[2024-02-21 02:06:45,862 : INFO : main : >>>>>>>>>>>>>>>> Stage Training completed <<<<<<<<<<<<<<<<

x====================x]
[2024-02-21 02:06:45,863 : INFO : main : ******************]
[2024-02-21 02:06:45,863 : INFO : main : >>>>>>>>>>>>>>>>> Stage Evaluation Stage started <<<<<<<<<<<<<<<<<<<]
[2024-02-21 02:06:45,866 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-21 02:06:45,870 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-21 02:06:45,870 : INFO : common : created directory at : artifacts]
[2024-02-21 02:09:44,509 : INFO : common : json file saved at : scores.json]
[2024-02-21 02:09:45,971 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-21 02:09:46,567 : INFO : builder_impl : Assets written to: C:\Users\Savi\AppData\Local\Temp\tmpm3p_v17e\model\data\model\assets]
[2024-02-21 02:09:54,081 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\1cee13125e5144bab9cc7c5596b9c54e\artifacts\model\data]
[2024-02-21 02:09:54,085 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\1cee13125e5144bab9cc7c5596b9c54e\artifacts\model\data\model]
[2024-02-21 02:09:54,085 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\1cee13125e5144bab9cc7c5596b9c54e\artifacts\model\data\model\assets]
[2024-02-21 02:09:54,093 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\1cee13125e5144bab9cc7c5596b9c54e\artifacts\model\data\model\variables]
[2024-02-21 02:09:54,278 : INFO : main : >>>>>>>>>>>>>> Stage Evaluation Stage completed <<<<<<<<<<<

x========================x]
[2024-02-21 02:28:57,582 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-21 02:28:57,587 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-21 02:28:57,588 : INFO : common : created directory at : artifacts]
[2024-02-21 02:31:07,129 : INFO : main : >>>>> Stage Data ingestion stage started <<<<<<<]
[2024-02-21 02:31:07,131 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-21 02:31:07,133 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-21 02:31:07,133 : INFO : common : created directory at : artifacts]
[2024-02-21 02:31:07,135 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-21 02:31:07,136 : INFO : data_ingestion : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-21 02:35:23,905 : INFO : data_ingestion : Downloaded data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-21 02:35:32,092 : INFO : main : >>>>>> Stage Data ingestion stage completed <<<<<<

x========================================x]
[2024-02-21 02:35:32,092 : INFO : main : ******************]
[2024-02-21 02:35:32,092 : INFO : main : >>>>>>>>> Stage Prepare Base Model started <<<<<<<<<<<]
[2024-02-21 02:35:32,098 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-21 02:35:32,103 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-21 02:35:32,104 : INFO : common : created directory at : artifacts]
[2024-02-21 02:35:32,104 : INFO : common : created directory at : artifacts/prepare_base_model]
[2024-02-21 02:35:32,538 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-21 02:35:32,904 : INFO : main : >>>>>>>>>> Stage Prepare Base Model completed <<<<<<<<<<<<

 x=============================x]
[2024-02-21 02:35:32,905 : INFO : main : **********************]
[2024-02-21 02:35:32,905 : INFO : main : >>>>>>>>>>>> Stage Training started <<<<<<<<<<<<<<<]
[2024-02-21 02:35:32,907 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-21 02:35:32,908 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-21 02:35:32,908 : INFO : common : created directory at : artifacts]
[2024-02-21 02:35:32,909 : INFO : common : created directory at : artifacts/training]
[2024-02-21 02:41:50,380 : INFO : main : >>>>>>>>>>>>>>>> Stage Training completed <<<<<<<<<<<<<<<<

x====================x]
[2024-02-21 02:41:50,380 : INFO : main : ******************]
[2024-02-21 02:41:50,381 : INFO : main : >>>>>>>>>>>>>>>>> Stage Evaluation Stage started <<<<<<<<<<<<<<<<<<<]
[2024-02-21 02:41:50,382 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-21 02:41:50,383 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-21 02:41:50,384 : INFO : common : created directory at : artifacts]
[2024-02-21 02:43:40,244 : INFO : common : json file saved at : scores.json]
[2024-02-21 02:43:41,524 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-21 02:43:42,245 : INFO : builder_impl : Assets written to: C:\Users\Savi\AppData\Local\Temp\tmp6po8gj10\model\data\model\assets]
[2024-02-21 02:43:54,983 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\5fd782079fc148158290dc7c07c95f12\artifacts\model\data]
[2024-02-21 02:43:54,985 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\5fd782079fc148158290dc7c07c95f12\artifacts\model\data\model]
[2024-02-21 02:43:54,986 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\5fd782079fc148158290dc7c07c95f12\artifacts\model\data\model\assets]
[2024-02-21 02:43:54,991 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\5fd782079fc148158290dc7c07c95f12\artifacts\model\data\model\variables]
[2024-02-21 02:43:55,095 : INFO : main : >>>>>>>>>>>>>> Stage Evaluation Stage completed <<<<<<<<<<<

x========================x]
[2024-02-21 02:44:20,992 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-21 02:44:20,995 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-21 02:44:20,997 : INFO : common : created directory at : artifacts]
[2024-02-21 02:46:15,502 : INFO : common : json file saved at : scores.json]
[2024-02-21 02:46:18,572 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-21 02:46:19,249 : INFO : builder_impl : Assets written to: C:\Users\Savi\AppData\Local\Temp\tmpfvcejwyh\model\data\model\assets]
[2024-02-21 03:07:51,833 : INFO : main : >>>>> Stage Data ingestion stage started <<<<<<<]
[2024-02-21 03:07:51,835 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-21 03:07:51,836 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-21 03:07:51,837 : INFO : common : created directory at : artifacts]
[2024-02-21 03:07:51,838 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-21 03:07:51,838 : INFO : data_ingestion : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-21 03:12:08,063 : INFO : data_ingestion : Downloaded data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-21 03:12:16,272 : INFO : main : >>>>>> Stage Data ingestion stage completed <<<<<<

x========================================x]
[2024-02-21 03:12:16,272 : INFO : main : ******************]
[2024-02-21 03:12:16,273 : INFO : main : >>>>>>>>> Stage Prepare Base Model started <<<<<<<<<<<]
[2024-02-21 03:12:16,275 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-21 03:12:16,276 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-21 03:12:16,277 : INFO : common : created directory at : artifacts]
[2024-02-21 03:12:16,278 : INFO : common : created directory at : artifacts/prepare_base_model]
[2024-02-21 03:12:16,594 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-21 03:12:16,804 : INFO : main : >>>>>>>>>> Stage Prepare Base Model completed <<<<<<<<<<<<

 x=============================x]
[2024-02-21 03:12:16,806 : INFO : main : **********************]
[2024-02-21 03:12:16,806 : INFO : main : >>>>>>>>>>>> Stage Training started <<<<<<<<<<<<<<<]
[2024-02-21 03:12:16,808 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-21 03:12:16,811 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-21 03:12:16,812 : INFO : common : created directory at : artifacts]
[2024-02-21 03:12:16,813 : INFO : common : created directory at : artifacts/training]
[2024-02-21 03:18:18,573 : INFO : main : >>>>>>>>>>>>>>>> Stage Training completed <<<<<<<<<<<<<<<<

x====================x]
[2024-02-21 03:18:18,574 : INFO : main : ******************]
[2024-02-21 03:18:18,575 : INFO : main : >>>>>>>>>>>>>>>>> Stage Evaluation Stage started <<<<<<<<<<<<<<<<<<<]
[2024-02-21 03:18:18,576 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-21 03:18:18,578 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-21 03:18:18,578 : INFO : common : created directory at : artifacts]
[2024-02-21 03:20:06,309 : INFO : common : json file saved at : scores.json]
[2024-02-21 03:20:07,432 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-21 03:20:08,153 : INFO : builder_impl : Assets written to: C:\Users\Savi\AppData\Local\Temp\tmpsj4udgpf\model\data\model\assets]
[2024-02-21 03:20:13,864 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\19d6672ba6b7484981779ab1342d6c19\artifacts\model\data]
[2024-02-21 03:20:13,867 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\19d6672ba6b7484981779ab1342d6c19\artifacts\model\data\model]
[2024-02-21 03:20:13,868 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\19d6672ba6b7484981779ab1342d6c19\artifacts\model\data\model\assets]
[2024-02-21 03:20:13,873 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\19d6672ba6b7484981779ab1342d6c19\artifacts\model\data\model\variables]
[2024-02-21 03:20:13,970 : INFO : main : >>>>>>>>>>>>>> Stage Evaluation Stage completed <<<<<<<<<<<

x========================x]
[2024-02-22 16:02:36,343 : INFO : main : >>>>> Stage Data ingestion stage started <<<<<<<]
[2024-02-22 16:02:36,349 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 16:02:36,354 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 16:02:36,355 : INFO : common : created directory at : artifacts]
[2024-02-22 16:02:36,356 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-22 16:02:36,357 : INFO : data_ingestion : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-22 16:06:50,143 : INFO : data_ingestion : Downloaded data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-22 16:06:57,574 : INFO : main : >>>>>> Stage Data ingestion stage completed <<<<<<

x========================================x]
[2024-02-22 16:06:57,575 : INFO : main : ******************]
[2024-02-22 16:06:57,575 : INFO : main : >>>>>>>>> Stage Prepare Base Model started <<<<<<<<<<<]
[2024-02-22 16:06:57,577 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 16:06:57,578 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 16:06:57,578 : INFO : common : created directory at : artifacts]
[2024-02-22 16:06:57,578 : INFO : common : created directory at : artifacts/prepare_base_model]
[2024-02-22 16:06:57,998 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-22 16:06:58,220 : INFO : main : >>>>>>>>>> Stage Prepare Base Model completed <<<<<<<<<<<<

 x=============================x]
[2024-02-22 16:06:58,220 : INFO : main : **********************]
[2024-02-22 16:06:58,221 : INFO : main : >>>>>>>>>>>> Stage Training started <<<<<<<<<<<<<<<]
[2024-02-22 16:06:58,222 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 16:06:58,223 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 16:06:58,224 : INFO : common : created directory at : artifacts]
[2024-02-22 16:06:58,224 : INFO : common : created directory at : artifacts/training]
[2024-02-22 16:16:57,667 : INFO : main : >>>>>>>>>>>>>>>> Stage Training completed <<<<<<<<<<<<<<<<

x====================x]
[2024-02-22 16:16:57,667 : INFO : main : ******************]
[2024-02-22 16:16:57,667 : INFO : main : >>>>>>>>>>>>>>>>> Stage Evaluation Stage started <<<<<<<<<<<<<<<<<<<]
[2024-02-22 16:16:57,671 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 16:16:57,671 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 16:16:57,671 : INFO : common : created directory at : artifacts]
[2024-02-22 16:19:53,320 : ERROR : main : API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "main.py", line 44, in <module>
    obj.main()
  File "c:\savi msi\complete data science\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_04_model_evaluation_mlflow.py", line 16, in main
    evaluation.log_into_mlflow()
  File "c:\savi msi\complete data science\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_evaluation_mlflow.py", line 58, in log_into_mlflow
    with mlflow.start_run():
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
[2024-02-22 16:21:47,720 : INFO : main : ******************]
[2024-02-22 16:21:47,720 : INFO : main : >>>>>>>>>>>>>>>>> Stage Evaluation Stage started <<<<<<<<<<<<<<<<<<<]
[2024-02-22 16:21:47,724 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 16:21:47,728 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 16:21:47,728 : INFO : common : created directory at : artifacts]
[2024-02-22 16:24:50,142 : ERROR : main : API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "main.py", line 44, in <module>
    obj.main()
  File "c:\savi msi\complete data science\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_04_model_evaluation_mlflow.py", line 16, in main
    evaluation.log_into_mlflow()
  File "c:\savi msi\complete data science\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_evaluation_mlflow.py", line 58, in log_into_mlflow
    with mlflow.start_run():
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
[2024-02-22 16:31:08,303 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 16:31:08,312 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 16:31:08,316 : INFO : common : created directory at : artifacts]
[2024-02-22 16:34:18,376 : INFO : common : json file saved at : scores.json]
[2024-02-22 16:40:10,902 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 16:40:10,907 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 16:40:10,911 : INFO : common : created directory at : artifacts]
[2024-02-22 16:43:19,515 : INFO : common : json file saved at : scores.json]
[2024-02-22 16:43:21,908 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-22 16:43:22,603 : INFO : builder_impl : Assets written to: C:\Users\Savi\AppData\Local\Temp\tmp0grboi37\model\data\model\assets]
[2024-02-22 16:46:10,083 : INFO : main : ******************]
[2024-02-22 16:46:10,083 : INFO : main : >>>>>>>>>>>>>>>>> Stage Evaluation Stage started <<<<<<<<<<<<<<<<<<<]
[2024-02-22 16:46:10,083 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 16:46:10,087 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 16:46:10,087 : INFO : common : created directory at : artifacts]
[2024-02-22 16:49:09,933 : INFO : common : json file saved at : scores.json]
[2024-02-22 16:49:10,592 : ERROR : main : API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "main.py", line 44, in <module>
    obj.main()
  File "c:\savi msi\complete data science\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_04_model_evaluation_mlflow.py", line 16, in main
    evaluation.log_into_mlflow()
  File "c:\savi msi\complete data science\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_evaluation_mlflow.py", line 58, in log_into_mlflow
    with mlflow.start_run():
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
[2024-02-22 17:05:49,242 : INFO : main : >>>>> Stage Data ingestion stage started <<<<<<<]
[2024-02-22 17:05:49,244 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 17:05:49,245 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 17:05:49,246 : INFO : common : created directory at : artifacts]
[2024-02-22 17:05:49,247 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-22 17:05:49,248 : INFO : data_ingestion : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-22 17:10:05,262 : INFO : data_ingestion : Downloaded data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-22 17:10:14,033 : INFO : main : >>>>>> Stage Data ingestion stage completed <<<<<<

x========================================x]
[2024-02-22 17:10:14,034 : INFO : main : ******************]
[2024-02-22 17:10:14,035 : INFO : main : >>>>>>>>> Stage Prepare Base Model started <<<<<<<<<<<]
[2024-02-22 17:10:14,038 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 17:10:14,040 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 17:10:14,041 : INFO : common : created directory at : artifacts]
[2024-02-22 17:10:14,041 : INFO : common : created directory at : artifacts/prepare_base_model]
[2024-02-22 17:10:14,428 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-22 17:10:14,635 : INFO : main : >>>>>>>>>> Stage Prepare Base Model completed <<<<<<<<<<<<

 x=============================x]
[2024-02-22 17:10:14,636 : INFO : main : **********************]
[2024-02-22 17:10:14,636 : INFO : main : >>>>>>>>>>>> Stage Training started <<<<<<<<<<<<<<<]
[2024-02-22 17:10:14,637 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 17:10:14,639 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 17:10:14,640 : INFO : common : created directory at : artifacts]
[2024-02-22 17:10:14,640 : INFO : common : created directory at : artifacts/training]
[2024-02-22 17:18:01,943 : INFO : main : >>>>>>>>>>>>>>>> Stage Training completed <<<<<<<<<<<<<<<<

x====================x]
[2024-02-22 17:18:01,944 : INFO : main : ******************]
[2024-02-22 17:18:01,945 : INFO : main : >>>>>>>>>>>>>>>>> Stage Evaluation Stage started <<<<<<<<<<<<<<<<<<<]
[2024-02-22 17:18:01,948 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 17:18:01,950 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 17:18:01,951 : INFO : common : created directory at : artifacts]
[2024-02-22 17:20:19,901 : INFO : common : json file saved at : scores.json]
[2024-02-22 17:21:22,237 : ERROR : main : API request to https://dagshub.com/sakshamwalia/kidney-disease-classification-deep-learning-project.mlflow/api/2.0/mlflow/runs/create failed with exception HTTPSConnectionPool(host='dagshub.com', port=443): Max retries exceeded with url: /sakshamwalia/kidney-disease-classification-deep-learning-project.mlflow/api/2.0/mlflow/runs/create (Caused by ResponseError('too many 502 error responses'))]
urllib3.exceptions.ResponseError: too many 502 error responses

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\urllib3\connectionpool.py", line 948, in urlopen
    return self.urlopen(
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\urllib3\connectionpool.py", line 948, in urlopen
    return self.urlopen(
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\urllib3\connectionpool.py", line 948, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\urllib3\connectionpool.py", line 938, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='dagshub.com', port=443): Max retries exceeded with url: /sakshamwalia/kidney-disease-classification-deep-learning-project.mlflow/api/2.0/mlflow/runs/create (Caused by ResponseError('too many 502 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 167, in http_request
    return _get_http_response_with_retries(
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 98, in _get_http_response_with_retries
    return session.request(method, url, **kwargs)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\requests\adapters.py", line 510, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='dagshub.com', port=443): Max retries exceeded with url: /sakshamwalia/kidney-disease-classification-deep-learning-project.mlflow/api/2.0/mlflow/runs/create (Caused by ResponseError('too many 502 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 44, in <module>
    obj.main()
  File "c:\savi msi\complete data science\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_04_model_evaluation_mlflow.py", line 16, in main
    evaluation.log_into_mlflow()
  File "c:\savi msi\complete data science\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_evaluation_mlflow.py", line 58, in log_into_mlflow
    with mlflow.start_run():
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 278, in call_endpoint
    response = http_request(
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 185, in http_request
    raise MlflowException(f"API request to {url} failed with exception {e}")
mlflow.exceptions.MlflowException: API request to https://dagshub.com/sakshamwalia/kidney-disease-classification-deep-learning-project.mlflow/api/2.0/mlflow/runs/create failed with exception HTTPSConnectionPool(host='dagshub.com', port=443): Max retries exceeded with url: /sakshamwalia/kidney-disease-classification-deep-learning-project.mlflow/api/2.0/mlflow/runs/create (Caused by ResponseError('too many 502 error responses'))
[2024-02-22 17:23:20,993 : INFO : main : ******************]
[2024-02-22 17:23:20,994 : INFO : main : >>>>>>>>>>>>>>>>> Stage Evaluation Stage started <<<<<<<<<<<<<<<<<<<]
[2024-02-22 17:23:20,999 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 17:23:21,001 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 17:23:21,002 : INFO : common : created directory at : artifacts]
[2024-02-22 17:25:35,050 : INFO : common : json file saved at : scores.json]
[2024-02-22 17:25:35,685 : ERROR : main : API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "main.py", line 44, in <module>
    obj.main()
  File "c:\savi msi\complete data science\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_04_model_evaluation_mlflow.py", line 16, in main
    evaluation.log_into_mlflow()
  File "c:\savi msi\complete data science\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_evaluation_mlflow.py", line 58, in log_into_mlflow
    with mlflow.start_run():
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
[2024-02-22 17:31:03,294 : INFO : main : ******************]
[2024-02-22 17:31:03,294 : INFO : main : >>>>>>>>>>>>>>>>> Stage Evaluation Stage started <<<<<<<<<<<<<<<<<<<]
[2024-02-22 17:31:03,297 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 17:31:03,298 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 17:31:03,298 : INFO : common : created directory at : artifacts]
[2024-02-22 17:33:20,858 : INFO : common : json file saved at : scores.json]
[2024-02-22 17:33:21,519 : ERROR : main : API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "main.py", line 44, in <module>
    obj.main()
  File "c:\savi msi\complete data science\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_04_model_evaluation_mlflow.py", line 16, in main
    evaluation.log_into_mlflow()
  File "c:\savi msi\complete data science\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_evaluation_mlflow.py", line 58, in log_into_mlflow
    with mlflow.start_run():
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
[2024-02-22 17:54:06,426 : INFO : main : >>>>> Stage Data ingestion stage started <<<<<<<]
[2024-02-22 17:54:06,428 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 17:54:06,429 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 17:54:06,429 : INFO : common : created directory at : artifacts]
[2024-02-22 17:54:06,431 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-22 17:54:06,432 : INFO : data_ingestion : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-22 17:58:14,336 : INFO : data_ingestion : Downloaded data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-22 17:58:22,901 : INFO : main : >>>>>> Stage Data ingestion stage completed <<<<<<

x========================================x]
[2024-02-22 17:58:22,902 : INFO : main : ******************]
[2024-02-22 17:58:22,902 : INFO : main : >>>>>>>>> Stage Prepare Base Model started <<<<<<<<<<<]
[2024-02-22 17:58:22,904 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 17:58:22,906 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 17:58:22,906 : INFO : common : created directory at : artifacts]
[2024-02-22 17:58:22,907 : INFO : common : created directory at : artifacts/prepare_base_model]
[2024-02-22 17:58:23,274 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-22 17:58:23,573 : INFO : main : >>>>>>>>>> Stage Prepare Base Model completed <<<<<<<<<<<<

 x=============================x]
[2024-02-22 17:58:23,574 : INFO : main : **********************]
[2024-02-22 17:58:23,575 : INFO : main : >>>>>>>>>>>> Stage Training started <<<<<<<<<<<<<<<]
[2024-02-22 17:58:23,577 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 17:58:23,578 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 17:58:23,579 : INFO : common : created directory at : artifacts]
[2024-02-22 17:58:23,580 : INFO : common : created directory at : artifacts/training]
[2024-02-22 18:06:16,085 : INFO : main : >>>>>>>>>>>>>>>> Stage Training completed <<<<<<<<<<<<<<<<

x====================x]
[2024-02-22 18:39:41,699 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 18:39:41,704 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 18:39:41,707 : INFO : common : created directory at : artifacts]
[2024-02-22 18:42:52,918 : INFO : common : json file saved at : scores.json]
[2024-02-22 18:42:56,200 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-22 18:42:56,856 : INFO : builder_impl : Assets written to: C:\Users\Savi\AppData\Local\Temp\tmpnumr2agq\model\data\model\assets]
[2024-02-22 18:48:34,283 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 18:48:34,299 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 18:48:34,302 : INFO : common : created directory at : artifacts]
[2024-02-22 18:51:44,996 : INFO : common : json file saved at : scores.json]
[2024-02-22 18:51:47,864 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-22 18:51:48,646 : INFO : builder_impl : Assets written to: C:\Users\Savi\AppData\Local\Temp\tmpw6p00g34\model\data\model\assets]
[2024-02-22 18:54:06,775 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 18:54:06,790 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 18:54:06,793 : INFO : common : created directory at : artifacts]
[2024-02-22 18:57:31,047 : INFO : common : json file saved at : scores.json]
[2024-02-22 18:57:34,129 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-22 18:57:34,767 : INFO : builder_impl : Assets written to: C:\Users\Savi\AppData\Local\Temp\tmpg981j8pn\model\data\model\assets]
[2024-02-22 19:06:55,206 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 19:06:55,210 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 19:06:55,214 : INFO : common : created directory at : artifacts]
[2024-02-22 19:10:09,441 : INFO : common : json file saved at : scores.json]
[2024-02-22 19:10:12,452 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-22 19:10:13,160 : INFO : builder_impl : Assets written to: C:\Users\Savi\AppData\Local\Temp\tmptl6qf8ky\model\data\model\assets]
[2024-02-22 19:27:45,177 : INFO : main : >>>>> Stage Data ingestion stage started <<<<<<<]
[2024-02-22 19:27:45,181 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 19:27:45,193 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 19:27:45,193 : INFO : common : created directory at : artifacts]
[2024-02-22 19:27:45,193 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-22 19:27:45,197 : INFO : data_ingestion : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-22 19:31:52,546 : INFO : data_ingestion : Downloaded data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-22 19:32:08,859 : INFO : main : >>>>>> Stage Data ingestion stage completed <<<<<<

x========================================x]
[2024-02-22 19:32:08,859 : INFO : main : ******************]
[2024-02-22 19:32:08,859 : INFO : main : >>>>>>>>> Stage Prepare Base Model started <<<<<<<<<<<]
[2024-02-22 19:32:08,863 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 19:32:08,867 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 19:32:08,867 : INFO : common : created directory at : artifacts]
[2024-02-22 19:32:08,867 : INFO : common : created directory at : artifacts/prepare_base_model]
[2024-02-22 19:32:09,438 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-22 19:32:09,786 : INFO : main : >>>>>>>>>> Stage Prepare Base Model completed <<<<<<<<<<<<

 x=============================x]
[2024-02-22 19:32:09,786 : INFO : main : **********************]
[2024-02-22 19:32:09,786 : INFO : main : >>>>>>>>>>>> Stage Training started <<<<<<<<<<<<<<<]
[2024-02-22 19:32:09,794 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 19:32:09,798 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 19:32:09,798 : INFO : common : created directory at : artifacts]
[2024-02-22 19:32:09,802 : INFO : common : created directory at : artifacts/training]
[2024-02-22 19:45:44,468 : INFO : main : >>>>>>>>>>>>>>>> Stage Training completed <<<<<<<<<<<<<<<<

x====================x]
[2024-02-22 19:45:44,469 : INFO : main : ******************]
[2024-02-22 19:45:44,469 : INFO : main : >>>>>>>>>>>>>>>>> Stage Evaluation Stage started <<<<<<<<<<<<<<<<<<<]
[2024-02-22 19:45:44,472 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 19:45:44,474 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 19:45:44,475 : INFO : common : created directory at : artifacts]
[2024-02-22 19:48:04,618 : INFO : common : json file saved at : scores.json]
[2024-02-22 19:48:06,012 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-22 19:48:06,717 : INFO : builder_impl : Assets written to: C:\Users\Savi\AppData\Local\Temp\tmpze3wm9zc\model\data\model\assets]
[2024-02-22 19:48:12,716 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\e99d95787dd6483c97b2a4e2db3830e1\artifacts\model\data]
[2024-02-22 19:48:12,718 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\e99d95787dd6483c97b2a4e2db3830e1\artifacts\model\data\model]
[2024-02-22 19:48:12,720 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\e99d95787dd6483c97b2a4e2db3830e1\artifacts\model\data\model\assets]
[2024-02-22 19:48:12,724 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\e99d95787dd6483c97b2a4e2db3830e1\artifacts\model\data\model\variables]
[2024-02-22 19:48:12,829 : INFO : main : >>>>>>>>>>>>>> Stage Evaluation Stage completed <<<<<<<<<<<

x========================x]
[2024-02-22 20:15:15,446 : INFO : main : >>>>> Stage Data ingestion stage started <<<<<<<]
[2024-02-22 20:15:15,450 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 20:15:15,457 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 20:15:15,458 : INFO : common : created directory at : artifacts]
[2024-02-22 20:15:15,458 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-22 20:15:15,460 : INFO : data_ingestion : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-22 20:19:38,382 : INFO : data_ingestion : Downloaded data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-22 20:19:47,042 : INFO : main : >>>>>> Stage Data ingestion stage completed <<<<<<

x========================================x]
[2024-02-22 20:19:47,042 : INFO : main : ******************]
[2024-02-22 20:19:47,043 : INFO : main : >>>>>>>>> Stage Prepare Base Model started <<<<<<<<<<<]
[2024-02-22 20:19:47,045 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 20:19:47,046 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 20:19:47,046 : INFO : common : created directory at : artifacts]
[2024-02-22 20:19:47,047 : INFO : common : created directory at : artifacts/prepare_base_model]
[2024-02-22 20:19:47,397 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-22 20:19:47,703 : INFO : main : >>>>>>>>>> Stage Prepare Base Model completed <<<<<<<<<<<<

 x=============================x]
[2024-02-22 20:19:47,704 : INFO : main : **********************]
[2024-02-22 20:19:47,704 : INFO : main : >>>>>>>>>>>> Stage Training started <<<<<<<<<<<<<<<]
[2024-02-22 20:19:47,706 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 20:19:47,708 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 20:19:47,708 : INFO : common : created directory at : artifacts]
[2024-02-22 20:19:47,709 : INFO : common : created directory at : artifacts/training]
[2024-02-22 20:35:31,473 : INFO : main : >>>>>>>>>>>>>>>> Stage Training completed <<<<<<<<<<<<<<<<

x====================x]
[2024-02-22 20:35:31,474 : INFO : main : ******************]
[2024-02-22 20:35:31,474 : INFO : main : >>>>>>>>>>>>>>>>> Stage Evaluation Stage started <<<<<<<<<<<<<<<<<<<]
[2024-02-22 20:35:31,477 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 20:35:31,479 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 20:35:31,479 : INFO : common : created directory at : artifacts]
[2024-02-22 20:37:52,020 : INFO : common : json file saved at : scores.json]
[2024-02-22 20:37:52,655 : ERROR : main : API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "main.py", line 44, in <module>
    obj.main()
  File "c:\savi msi\complete data science\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_04_model_evaluation_mlflow.py", line 16, in main
    evaluation.log_into_mlflow()
  File "c:\savi msi\complete data science\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_evaluation_mlflow.py", line 57, in log_into_mlflow
    with mlflow.start_run():
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
[2024-02-22 20:44:00,788 : INFO : main : >>>>> Stage Data ingestion stage started <<<<<<<]
[2024-02-22 20:44:00,791 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 20:44:00,793 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 20:44:00,793 : INFO : common : created directory at : artifacts]
[2024-02-22 20:44:00,794 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-22 20:44:00,795 : INFO : data_ingestion : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-22 20:48:16,284 : INFO : data_ingestion : Downloaded data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-22 20:48:24,600 : INFO : main : >>>>>> Stage Data ingestion stage completed <<<<<<

x========================================x]
[2024-02-22 20:48:24,600 : INFO : main : ******************]
[2024-02-22 20:48:24,601 : INFO : main : >>>>>>>>> Stage Prepare Base Model started <<<<<<<<<<<]
[2024-02-22 20:48:24,602 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 20:48:24,604 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 20:48:24,605 : INFO : common : created directory at : artifacts]
[2024-02-22 20:48:24,605 : INFO : common : created directory at : artifacts/prepare_base_model]
[2024-02-22 20:48:24,960 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-22 20:48:25,163 : INFO : main : >>>>>>>>>> Stage Prepare Base Model completed <<<<<<<<<<<<

 x=============================x]
[2024-02-22 20:48:25,164 : INFO : main : **********************]
[2024-02-22 20:48:25,164 : INFO : main : >>>>>>>>>>>> Stage Training started <<<<<<<<<<<<<<<]
[2024-02-22 20:48:25,166 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 20:48:25,168 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 20:48:25,168 : INFO : common : created directory at : artifacts]
[2024-02-22 20:48:25,168 : INFO : common : created directory at : artifacts/training]
[2024-02-22 21:04:13,080 : INFO : main : >>>>>>>>>>>>>>>> Stage Training completed <<<<<<<<<<<<<<<<

x====================x]
[2024-02-22 21:04:13,081 : INFO : main : ******************]
[2024-02-22 21:04:13,081 : INFO : main : >>>>>>>>>>>>>>>>> Stage Evaluation Stage started <<<<<<<<<<<<<<<<<<<]
[2024-02-22 21:04:13,083 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 21:04:13,085 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 21:04:13,085 : INFO : common : created directory at : artifacts]
[2024-02-22 21:06:32,202 : INFO : common : json file saved at : scores.json]
[2024-02-22 21:06:33,447 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-22 21:06:33,995 : INFO : builder_impl : Assets written to: C:\Users\Savi\AppData\Local\Temp\tmpx_hr3sah\model\data\model\assets]
[2024-02-22 21:06:39,910 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\145442fb65974776b0f27af96546db4e\artifacts\model\data]
[2024-02-22 21:06:39,912 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\145442fb65974776b0f27af96546db4e\artifacts\model\data\model]
[2024-02-22 21:06:39,913 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\145442fb65974776b0f27af96546db4e\artifacts\model\data\model\assets]
[2024-02-22 21:06:39,919 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\145442fb65974776b0f27af96546db4e\artifacts\model\data\model\variables]
[2024-02-22 21:06:40,034 : INFO : main : >>>>>>>>>>>>>> Stage Evaluation Stage completed <<<<<<<<<<<

x========================x]
[2024-02-22 21:43:52,652 : INFO : main : >>>>> Stage Data ingestion stage started <<<<<<<]
[2024-02-22 21:43:52,668 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 21:43:52,668 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 21:43:52,668 : INFO : common : created directory at : artifacts]
[2024-02-22 21:43:52,668 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-22 21:43:52,668 : INFO : data_ingestion : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-22 21:48:02,619 : INFO : data_ingestion : Downloaded data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-22 21:48:12,452 : INFO : main : >>>>>> Stage Data ingestion stage completed <<<<<<

x========================================x]
[2024-02-22 21:48:12,452 : INFO : main : ******************]
[2024-02-22 21:48:12,452 : INFO : main : >>>>>>>>> Stage Prepare Base Model started <<<<<<<<<<<]
[2024-02-22 21:48:12,452 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 21:48:12,452 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 21:48:12,452 : INFO : common : created directory at : artifacts]
[2024-02-22 21:48:12,452 : INFO : common : created directory at : artifacts/prepare_base_model]
[2024-02-22 21:48:12,905 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-22 21:48:13,198 : INFO : main : >>>>>>>>>> Stage Prepare Base Model completed <<<<<<<<<<<<

 x=============================x]
[2024-02-22 21:48:13,198 : INFO : main : **********************]
[2024-02-22 21:48:13,198 : INFO : main : >>>>>>>>>>>> Stage Training started <<<<<<<<<<<<<<<]
[2024-02-22 21:48:13,198 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 21:48:13,198 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 21:48:13,198 : INFO : common : created directory at : artifacts]
[2024-02-22 21:48:13,198 : INFO : common : created directory at : artifacts/training]
[2024-02-22 21:55:56,814 : INFO : main : >>>>>>>>>>>>>>>> Stage Training completed <<<<<<<<<<<<<<<<

x====================x]
[2024-02-22 21:55:56,814 : INFO : main : ******************]
[2024-02-22 21:55:56,814 : INFO : main : >>>>>>>>>>>>>>>>> Stage Evaluation Stage started <<<<<<<<<<<<<<<<<<<]
[2024-02-22 21:55:56,814 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 21:55:56,814 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 21:55:56,814 : INFO : common : created directory at : artifacts]
[2024-02-22 21:58:36,156 : INFO : common : json file saved at : scores.json]
[2024-02-22 21:58:36,964 : ERROR : main : API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "main.py", line 44, in <module>
    obj.main()
  File "c:\savi msi\complete data science\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_04_model_evaluation_mlflow.py", line 16, in main
    evaluation.log_into_mlflow()
  File "c:\savi msi\complete data science\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_evaluation_mlflow.py", line 56, in log_into_mlflow
    with mlflow.start_run():
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\tracking\fluent.py", line 350, in start_run
    active_run_obj = client.create_run(
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 275, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 131, in create_run
    return self.store.create_run(
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 175, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
[2024-02-22 23:11:51,860 : INFO : main : >>>>> Stage Data ingestion stage started <<<<<<<]
[2024-02-22 23:11:51,876 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 23:11:51,876 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 23:11:51,876 : INFO : common : created directory at : artifacts]
[2024-02-22 23:11:51,876 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-22 23:11:51,876 : INFO : data_ingestion : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-22 23:16:18,186 : INFO : data_ingestion : Downloaded data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-22 23:16:33,933 : INFO : main : >>>>>> Stage Data ingestion stage completed <<<<<<

x========================================x]
[2024-02-22 23:16:33,933 : INFO : main : ******************]
[2024-02-22 23:16:33,933 : INFO : main : >>>>>>>>> Stage Prepare Base Model started <<<<<<<<<<<]
[2024-02-22 23:16:33,933 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 23:16:33,933 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 23:16:33,945 : INFO : common : created directory at : artifacts]
[2024-02-22 23:16:33,946 : INFO : common : created directory at : artifacts/prepare_base_model]
[2024-02-22 23:16:34,704 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-22 23:16:35,025 : INFO : main : >>>>>>>>>> Stage Prepare Base Model completed <<<<<<<<<<<<

 x=============================x]
[2024-02-22 23:16:35,025 : INFO : main : **********************]
[2024-02-22 23:16:35,027 : INFO : main : >>>>>>>>>>>> Stage Training started <<<<<<<<<<<<<<<]
[2024-02-22 23:16:35,029 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 23:16:35,029 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 23:16:35,029 : INFO : common : created directory at : artifacts]
[2024-02-22 23:16:35,036 : INFO : common : created directory at : artifacts/training]
[2024-02-22 23:27:40,976 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-22 23:27:41,834 : INFO : builder_impl : Assets written to: C:\Users\Savi\AppData\Local\Temp\tmp43ylxn04\model\data\model\assets]
[2024-02-22 23:27:51,658 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\2228686d8e9c49408f2d06f2dce6b931\artifacts\model\data]
[2024-02-22 23:27:51,658 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\2228686d8e9c49408f2d06f2dce6b931\artifacts\model\data\model]
[2024-02-22 23:27:51,658 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\2228686d8e9c49408f2d06f2dce6b931\artifacts\model\data\model\assets]
[2024-02-22 23:27:51,673 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\2228686d8e9c49408f2d06f2dce6b931\artifacts\model\data\model\variables]
[2024-02-22 23:27:51,798 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\2228686d8e9c49408f2d06f2dce6b931\artifacts\tensorboard_logs\train]
[2024-02-22 23:27:51,814 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\2228686d8e9c49408f2d06f2dce6b931\artifacts\tensorboard_logs\validation]
[2024-02-22 23:27:51,892 : INFO : main : >>>>>>>>>>>>>>>> Stage Training completed <<<<<<<<<<<<<<<<

x====================x]
[2024-02-22 23:27:51,892 : INFO : main : ******************]
[2024-02-22 23:27:51,892 : INFO : main : >>>>>>>>>>>>>>>>> Stage Evaluation Stage started <<<<<<<<<<<<<<<<<<<]
[2024-02-22 23:27:51,892 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 23:27:51,907 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 23:27:51,907 : INFO : common : created directory at : artifacts]
[2024-02-22 23:31:10,176 : INFO : common : json file saved at : scores.json]
[2024-02-22 23:31:11,261 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-22 23:31:11,831 : INFO : builder_impl : Assets written to: C:\Users\Savi\AppData\Local\Temp\tmp4netssa9\model\data\model\assets]
[2024-02-22 23:31:17,859 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\20283688c8ee4c97899a7bbcbc3a146b\artifacts\model\data]
[2024-02-22 23:31:17,859 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\20283688c8ee4c97899a7bbcbc3a146b\artifacts\model\data\model]
[2024-02-22 23:31:17,867 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\20283688c8ee4c97899a7bbcbc3a146b\artifacts\model\data\model\assets]
[2024-02-22 23:31:17,867 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\20283688c8ee4c97899a7bbcbc3a146b\artifacts\model\data\model\variables]
[2024-02-22 23:31:17,964 : INFO : main : >>>>>>>>>>>>>> Stage Evaluation Stage completed <<<<<<<<<<<

x========================x]
[2024-02-22 23:47:52,342 : INFO : main : >>>>> Stage Data ingestion stage started <<<<<<<]
[2024-02-22 23:47:52,342 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 23:47:52,342 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 23:47:52,342 : INFO : common : created directory at : artifacts]
[2024-02-22 23:47:52,342 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-22 23:47:52,349 : INFO : data_ingestion : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-22 23:52:15,525 : INFO : data_ingestion : Downloaded data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-22 23:52:24,659 : INFO : main : >>>>>> Stage Data ingestion stage completed <<<<<<

x========================================x]
[2024-02-22 23:52:24,660 : INFO : main : ******************]
[2024-02-22 23:52:24,660 : INFO : main : >>>>>>>>> Stage Prepare Base Model started <<<<<<<<<<<]
[2024-02-22 23:52:24,662 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 23:52:24,665 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 23:52:24,665 : INFO : common : created directory at : artifacts]
[2024-02-22 23:52:24,666 : INFO : common : created directory at : artifacts/prepare_base_model]
[2024-02-22 23:52:25,067 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-22 23:52:25,299 : INFO : main : >>>>>>>>>> Stage Prepare Base Model completed <<<<<<<<<<<<

 x=============================x]
[2024-02-22 23:52:25,299 : INFO : main : **********************]
[2024-02-22 23:52:25,301 : INFO : main : >>>>>>>>>>>> Stage Training started <<<<<<<<<<<<<<<]
[2024-02-22 23:52:25,302 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-22 23:52:25,304 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-22 23:52:25,305 : INFO : common : created directory at : artifacts]
[2024-02-22 23:52:25,306 : INFO : common : created directory at : artifacts/training]
[2024-02-23 00:06:08,021 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-23 00:06:08,522 : INFO : builder_impl : Assets written to: C:\Users\Savi\AppData\Local\Temp\tmp20qhz1z3\model\data\model\assets]
[2024-02-23 00:06:14,409 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\a7adf950444f47dca89a372c9aabad47\artifacts\model\data]
[2024-02-23 00:06:14,413 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\a7adf950444f47dca89a372c9aabad47\artifacts\model\data\model]
[2024-02-23 00:06:14,414 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\a7adf950444f47dca89a372c9aabad47\artifacts\model\data\model\assets]
[2024-02-23 00:06:14,420 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\a7adf950444f47dca89a372c9aabad47\artifacts\model\data\model\variables]
[2024-02-23 00:06:14,524 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\a7adf950444f47dca89a372c9aabad47\artifacts\tensorboard_logs\train]
[2024-02-23 00:06:14,531 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\a7adf950444f47dca89a372c9aabad47\artifacts\tensorboard_logs\validation]
[2024-02-23 00:06:14,606 : INFO : main : >>>>>>>>>>>>>>>> Stage Training completed <<<<<<<<<<<<<<<<

x====================x]
[2024-02-23 00:06:14,607 : INFO : main : ******************]
[2024-02-23 00:06:14,607 : INFO : main : >>>>>>>>>>>>>>>>> Stage Evaluation Stage started <<<<<<<<<<<<<<<<<<<]
[2024-02-23 00:06:14,609 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-23 00:06:14,611 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-23 00:06:14,612 : INFO : common : created directory at : artifacts]
[2024-02-23 00:08:15,829 : INFO : common : json file saved at : scores.json]
[2024-02-23 00:08:17,052 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-23 00:08:17,867 : INFO : builder_impl : Assets written to: C:\Users\Savi\AppData\Local\Temp\tmpeea8osom\model\data\model\assets]
[2024-02-23 00:08:26,172 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\d716befe8783427290746636738cf029\artifacts\model\data]
[2024-02-23 00:08:26,174 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\d716befe8783427290746636738cf029\artifacts\model\data\model]
[2024-02-23 00:08:26,176 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\d716befe8783427290746636738cf029\artifacts\model\data\model\assets]
[2024-02-23 00:08:26,181 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\d716befe8783427290746636738cf029\artifacts\model\data\model\variables]
[2024-02-23 00:08:26,303 : INFO : main : >>>>>>>>>>>>>> Stage Evaluation Stage completed <<<<<<<<<<<

x========================x]
[2024-02-23 00:19:11,560 : INFO : main : >>>>> Stage Data ingestion stage started <<<<<<<]
[2024-02-23 00:19:11,563 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-23 00:19:11,570 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-23 00:19:11,572 : INFO : common : created directory at : artifacts]
[2024-02-23 00:19:11,573 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-23 00:19:11,574 : INFO : data_ingestion : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-23 00:23:45,234 : INFO : data_ingestion : Downloaded data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-23 00:23:55,550 : INFO : main : >>>>>> Stage Data ingestion stage completed <<<<<<

x========================================x]
[2024-02-23 00:23:55,550 : INFO : main : ******************]
[2024-02-23 00:23:55,551 : INFO : main : >>>>>>>>> Stage Prepare Base Model started <<<<<<<<<<<]
[2024-02-23 00:23:55,554 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-23 00:23:55,555 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-23 00:23:55,555 : INFO : common : created directory at : artifacts]
[2024-02-23 00:23:55,555 : INFO : common : created directory at : artifacts/prepare_base_model]
[2024-02-23 00:23:55,982 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-23 00:23:56,314 : INFO : main : >>>>>>>>>> Stage Prepare Base Model completed <<<<<<<<<<<<

 x=============================x]
[2024-02-23 00:23:56,314 : INFO : main : **********************]
[2024-02-23 00:23:56,315 : INFO : main : >>>>>>>>>>>> Stage Training started <<<<<<<<<<<<<<<]
[2024-02-23 00:23:56,317 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-23 00:23:56,318 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-23 00:23:56,319 : INFO : common : created directory at : artifacts]
[2024-02-23 00:23:56,319 : INFO : common : created directory at : artifacts/training]
[2024-02-23 00:44:27,731 : INFO : main : >>>>>>>>>>>>>>>> Stage Training completed <<<<<<<<<<<<<<<<

x====================x]
[2024-02-23 00:44:27,732 : INFO : main : ******************]
[2024-02-23 00:44:27,732 : INFO : main : >>>>>>>>>>>>>>>>> Stage Evaluation Stage started <<<<<<<<<<<<<<<<<<<]
[2024-02-23 00:44:27,734 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-23 00:44:27,735 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-23 00:44:27,736 : INFO : common : created directory at : artifacts]
[2024-02-23 00:46:37,289 : INFO : common : json file saved at : scores.json]
[2024-02-23 00:46:38,801 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-23 00:46:39,496 : INFO : builder_impl : Assets written to: C:\Users\Savi\AppData\Local\Temp\tmp4u2xboba\model\data\model\assets]
[2024-02-23 00:46:47,229 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\ccd83362ec52445892ac66334499cb6d\artifacts\model\data]
[2024-02-23 00:46:47,232 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\ccd83362ec52445892ac66334499cb6d\artifacts\model\data\model]
[2024-02-23 00:46:47,234 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\ccd83362ec52445892ac66334499cb6d\artifacts\model\data\model\assets]
[2024-02-23 00:46:47,239 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\ccd83362ec52445892ac66334499cb6d\artifacts\model\data\model\variables]
[2024-02-23 00:46:47,342 : INFO : main : >>>>>>>>>>>>>> Stage Evaluation Stage completed <<<<<<<<<<<

x========================x]
[2024-02-23 16:04:49,919 : INFO : main : >>>>> Stage Data ingestion stage started <<<<<<<]
[2024-02-23 16:04:49,926 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-23 16:04:49,932 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-23 16:04:49,932 : INFO : common : created directory at : artifacts]
[2024-02-23 16:04:49,933 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-23 16:04:49,934 : INFO : data_ingestion : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-23 16:13:47,475 : INFO : stage_01_data_ingestion : >>>>> Stage Data ingestion stage started <<<<<<<]
[2024-02-23 16:13:47,478 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-23 16:13:47,478 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-23 16:13:47,480 : INFO : common : created directory at : artifacts]
[2024-02-23 16:13:47,481 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-23 16:13:47,481 : INFO : data_ingestion : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-23 16:18:31,535 : INFO : data_ingestion : Downloaded data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-23 16:18:41,156 : INFO : stage_01_data_ingestion : >>>>>> Stage Data ingestion stage completed <<<<<<

x===========x]
[2024-02-23 16:22:25,929 : INFO : stage_01_data_ingestion : >>>>> Stage Data ingestion stage started <<<<<<<]
[2024-02-23 16:22:25,932 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-23 16:22:25,933 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-23 16:22:25,934 : INFO : common : created directory at : artifacts]
[2024-02-23 16:22:25,934 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-23 16:22:25,935 : INFO : data_ingestion : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-23 16:22:55,024 : INFO : stage_01_data_ingestion : >>>>> Stage Data ingestion stage started <<<<<<<]
[2024-02-23 16:22:55,027 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-23 16:22:55,028 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-23 16:22:55,029 : INFO : common : created directory at : artifacts]
[2024-02-23 16:22:55,031 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-23 16:22:55,032 : INFO : data_ingestion : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-23 16:27:30,023 : INFO : data_ingestion : Downloaded data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-23 16:27:38,755 : INFO : stage_01_data_ingestion : >>>>>> Stage Data ingestion stage completed <<<<<<

x===========x]
[2024-02-23 16:40:01,773 : INFO : stage_01_data_ingestion : >>>>> Stage Data ingestion stage started <<<<<<<]
[2024-02-23 16:40:01,777 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-23 16:40:01,779 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-23 16:40:01,779 : INFO : common : created directory at : artifacts]
[2024-02-23 16:40:01,780 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-23 16:40:01,781 : INFO : data_ingestion : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-23 16:44:45,027 : INFO : data_ingestion : Downloaded data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-23 16:44:51,921 : INFO : stage_01_data_ingestion : >>>>>> Stage Data ingestion stage completed <<<<<<

x===========x]
[2024-02-23 16:47:22,656 : INFO : stage_01_data_ingestion : >>>>> Stage Data ingestion stage started <<<<<<<]
[2024-02-23 16:47:22,656 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-23 16:47:22,661 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-23 16:47:22,661 : INFO : common : created directory at : artifacts]
[2024-02-23 16:47:22,663 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-23 16:47:22,663 : INFO : data_ingestion : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-23 16:49:34,439 : INFO : stage_01_data_ingestion : >>>>> Stage Data ingestion stage started <<<<<<<]
[2024-02-23 16:49:34,443 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-23 16:49:34,443 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-23 16:49:34,447 : INFO : common : created directory at : artifacts]
[2024-02-23 16:49:34,447 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-23 16:49:34,448 : INFO : data_ingestion : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-23 16:54:19,831 : INFO : data_ingestion : Downloaded data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-23 16:54:31,169 : INFO : stage_01_data_ingestion : >>>>>> Stage Data ingestion stage completed <<<<<<

x===========x]
[2024-02-23 17:07:02,519 : INFO : main : >>>>> Stage Data ingestion stage started <<<<<<<]
[2024-02-23 17:07:02,519 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-23 17:07:02,523 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-23 17:07:02,523 : INFO : common : created directory at : artifacts]
[2024-02-23 17:07:02,523 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-23 17:07:02,527 : INFO : data_ingestion : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-23 17:11:52,680 : INFO : data_ingestion : Downloaded data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-23 17:12:04,056 : INFO : main : >>>>>> Stage Data ingestion stage completed <<<<<<

x========================================x]
[2024-02-23 17:12:04,056 : INFO : main : ******************]
[2024-02-23 17:12:04,056 : INFO : main : >>>>>>>>> Stage Prepare Base Model started <<<<<<<<<<<]
[2024-02-23 17:12:04,056 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-23 17:12:04,060 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-23 17:12:04,060 : INFO : common : created directory at : artifacts]
[2024-02-23 17:12:04,060 : INFO : common : created directory at : artifacts/prepare_base_model]
[2024-02-23 17:12:04,778 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-23 17:12:05,039 : INFO : main : >>>>>>>>>> Stage Prepare Base Model completed <<<<<<<<<<<<

 x=============================x]
[2024-02-23 17:12:05,039 : INFO : main : **********************]
[2024-02-23 17:12:05,039 : INFO : main : >>>>>>>>>>>> Stage Training started <<<<<<<<<<<<<<<]
[2024-02-23 17:12:05,043 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-23 17:12:05,043 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-23 17:12:05,047 : INFO : common : created directory at : artifacts]
[2024-02-23 17:12:05,047 : INFO : common : created directory at : artifacts/training]
[2024-02-23 17:22:09,335 : INFO : main : >>>>>>>>>>>>>>>> Stage Training completed <<<<<<<<<<<<<<<<

x====================x]
[2024-02-23 17:22:09,339 : INFO : main : ******************]
[2024-02-23 17:22:09,339 : INFO : main : >>>>>>>>>>>>>>>>> Stage Evaluation Stage started <<<<<<<<<<<<<<<<<<<]
[2024-02-23 17:22:09,339 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-23 17:22:09,343 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-23 17:22:09,343 : INFO : common : created directory at : artifacts]
[2024-02-23 17:25:07,842 : INFO : common : json file saved at : scores.json]
[2024-02-23 17:25:09,476 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-23 17:25:10,246 : INFO : builder_impl : Assets written to: C:\Users\Savi\AppData\Local\Temp\tmphy6lfnmw\model\data\model\assets]
[2024-02-23 17:25:19,254 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\a509e6d9532943f6a9f84d53985367a1\artifacts\model\data]
[2024-02-23 17:25:19,258 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\a509e6d9532943f6a9f84d53985367a1\artifacts\model\data\model]
[2024-02-23 17:25:19,259 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\a509e6d9532943f6a9f84d53985367a1\artifacts\model\data\model\assets]
[2024-02-23 17:25:19,263 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\a509e6d9532943f6a9f84d53985367a1\artifacts\model\data\model\variables]
[2024-02-23 17:25:19,370 : INFO : main : >>>>>>>>>>>>>> Stage Evaluation Stage completed <<<<<<<<<<<

x========================x]
[2024-02-23 17:30:06,877 : INFO : stage_01_data_ingestion : >>>>> Stage Data ingestion stage started <<<<<<<]
[2024-02-23 17:30:06,877 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-23 17:30:06,881 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-23 17:30:06,881 : INFO : common : created directory at : artifacts]
[2024-02-23 17:30:06,881 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-23 17:30:06,884 : INFO : data_ingestion : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-23 17:34:27,701 : INFO : data_ingestion : Downloaded data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-23 17:34:38,724 : INFO : stage_01_data_ingestion : >>>>>> Stage Data ingestion stage completed <<<<<<

x===========x]
[2024-02-23 17:47:34,154 : INFO : main : >>>>> Stage Data ingestion stage started <<<<<<<]
[2024-02-23 17:47:34,158 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-23 17:47:34,160 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-23 17:47:34,161 : INFO : common : created directory at : artifacts]
[2024-02-23 17:47:34,161 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-23 17:47:34,162 : INFO : data_ingestion : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-23 17:51:42,383 : INFO : data_ingestion : Downloaded data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-23 17:51:58,331 : INFO : main : >>>>>> Stage Data ingestion stage completed <<<<<<

x========================================x]
[2024-02-23 17:51:58,331 : INFO : main : ******************]
[2024-02-23 17:51:58,332 : INFO : main : >>>>>>>>> Stage Prepare Base Model started <<<<<<<<<<<]
[2024-02-23 17:51:58,335 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-23 17:51:58,339 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-23 17:51:58,340 : INFO : common : created directory at : artifacts]
[2024-02-23 17:51:58,342 : INFO : common : created directory at : artifacts/prepare_base_model]
[2024-02-23 17:51:59,128 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-23 17:51:59,514 : INFO : main : >>>>>>>>>> Stage Prepare Base Model completed <<<<<<<<<<<<

 x=============================x]
[2024-02-23 17:51:59,514 : INFO : main : **********************]
[2024-02-23 17:51:59,518 : INFO : main : >>>>>>>>>>>> Stage Training started <<<<<<<<<<<<<<<]
[2024-02-23 17:51:59,519 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-23 17:51:59,525 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-23 17:51:59,527 : INFO : common : created directory at : artifacts]
[2024-02-23 17:51:59,528 : INFO : common : created directory at : artifacts/training]
[2024-02-23 18:03:39,000 : INFO : main : >>>>>>>>>>>>>>>> Stage Training completed <<<<<<<<<<<<<<<<

x====================x]
[2024-02-23 18:03:39,001 : INFO : main : ******************]
[2024-02-23 18:03:39,001 : INFO : main : >>>>>>>>>>>>>>>>> Stage Evaluation Stage started <<<<<<<<<<<<<<<<<<<]
[2024-02-23 18:03:39,003 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-23 18:03:39,004 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-23 18:03:39,004 : INFO : common : created directory at : artifacts]
[2024-02-23 18:05:27,936 : INFO : common : json file saved at : scores.json]
[2024-02-23 18:05:27,937 : INFO : common : json file saved at : scores.json]
[2024-02-23 18:05:29,117 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-23 18:05:29,768 : INFO : builder_impl : Assets written to: C:\Users\Savi\AppData\Local\Temp\tmppr3kumvt\model\data\model\assets]
[2024-02-23 18:05:35,655 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\795f87012d8f49a8b55289b47f56419a\artifacts\model\data]
[2024-02-23 18:05:35,659 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\795f87012d8f49a8b55289b47f56419a\artifacts\model\data\model]
[2024-02-23 18:05:35,661 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\795f87012d8f49a8b55289b47f56419a\artifacts\model\data\model\assets]
[2024-02-23 18:05:35,667 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\795f87012d8f49a8b55289b47f56419a\artifacts\model\data\model\variables]
[2024-02-23 18:05:35,770 : INFO : main : >>>>>>>>>>>>>> Stage Evaluation Stage completed <<<<<<<<<<<

x========================x]
[2024-02-23 18:18:41,265 : INFO : stage_01_data_ingestion : >>>>> Stage Data ingestion stage started <<<<<<<]
[2024-02-23 18:18:41,269 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-23 18:18:41,272 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-23 18:18:41,272 : INFO : common : created directory at : artifacts]
[2024-02-23 18:18:41,273 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-23 18:18:41,276 : INFO : data_ingestion : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-23 18:22:56,536 : INFO : data_ingestion : Downloaded data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-23 18:23:05,382 : INFO : stage_01_data_ingestion : >>>>>> Stage Data ingestion stage completed <<<<<<

x===========x]
[2024-02-23 20:07:41,118 : INFO : stage_01_data_ingestion : >>>>> Stage Data ingestion stage started <<<<<<<]
[2024-02-23 20:07:41,125 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-23 20:07:41,130 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-23 20:07:41,130 : INFO : common : created directory at : artifacts]
[2024-02-23 20:07:41,131 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-23 20:07:41,132 : INFO : data_ingestion : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-23 20:12:03,421 : INFO : data_ingestion : Downloaded data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-23 20:12:14,339 : INFO : stage_01_data_ingestion : >>>>>> Stage Data ingestion stage completed <<<<<<

x===========x]
[2024-02-23 20:35:43,089 : INFO : stage_01_data_ingestion : >>>>> Stage Data ingestion stage started <<<<<<<]
[2024-02-23 20:35:43,093 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-23 20:35:43,095 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-23 20:35:43,096 : INFO : common : created directory at : artifacts]
[2024-02-23 20:35:43,097 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-23 20:35:43,097 : INFO : data_ingestion : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-23 20:39:53,837 : INFO : data_ingestion : Downloaded data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-23 20:40:12,878 : INFO : stage_01_data_ingestion : >>>>>> Stage Data ingestion stage completed <<<<<<

x===========x]
[2024-02-23 20:46:32,740 : INFO : stage_01_data_ingestion : >>>>> Stage Data ingestion stage started <<<<<<<]
[2024-02-23 20:46:32,743 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-23 20:46:32,746 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-23 20:46:32,746 : INFO : common : created directory at : artifacts]
[2024-02-23 20:46:32,747 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-23 20:46:32,747 : INFO : data_ingestion : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-23 20:50:43,661 : INFO : data_ingestion : Downloaded data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-23 20:50:55,578 : INFO : stage_01_data_ingestion : >>>>>> Stage Data ingestion stage completed <<<<<<

x===========x]
[2024-02-23 21:05:03,308 : INFO : stage_01_data_ingestion : >>>>> Stage Data ingestion stage started <<<<<<<]
[2024-02-23 21:05:03,312 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-23 21:05:03,314 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-23 21:05:03,315 : INFO : common : created directory at : artifacts]
[2024-02-23 21:05:03,316 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-23 21:05:03,316 : INFO : data_ingestion : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-23 21:09:19,713 : INFO : data_ingestion : Downloaded data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-23 21:09:27,604 : INFO : stage_01_data_ingestion : >>>>>> Stage Data ingestion stage completed <<<<<<

x===========x]
[2024-02-23 21:14:01,198 : INFO : stage_01_data_ingestion : >>>>> Stage Data ingestion stage started <<<<<<<]
[2024-02-23 21:14:01,200 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-23 21:14:01,202 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-23 21:14:01,202 : INFO : common : created directory at : artifacts]
[2024-02-23 21:14:01,203 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-23 21:14:01,203 : INFO : data_ingestion : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-23 21:18:12,065 : INFO : data_ingestion : Downloaded data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-23 21:18:19,413 : INFO : stage_01_data_ingestion : >>>>>> Stage Data ingestion stage completed <<<<<<

x===========x]
[2024-02-23 21:27:43,147 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-23 21:27:43,149 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-23 21:27:43,150 : INFO : common : created directory at : artifacts]
[2024-02-23 21:27:43,151 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-23 21:27:43,153 : INFO : 919924381 : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-23 21:33:13,159 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-23 21:33:13,161 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-23 21:33:13,162 : INFO : common : created directory at : artifacts]
[2024-02-23 21:33:13,163 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-23 21:33:13,163 : INFO : 3203182107 : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-23 21:33:50,500 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-23 21:33:50,502 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-23 21:33:50,502 : INFO : common : created directory at : artifacts]
[2024-02-23 21:33:50,503 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-23 21:33:50,505 : INFO : 1966410251 : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-23 21:39:45,225 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-23 21:39:45,227 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-23 21:39:45,228 : INFO : common : created directory at : artifacts]
[2024-02-23 21:39:45,229 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-23 21:39:45,230 : INFO : 3203182107 : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-23 21:40:30,444 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-23 21:40:30,446 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-23 21:40:30,446 : INFO : common : created directory at : artifacts]
[2024-02-23 21:40:30,447 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-23 21:40:30,448 : INFO : 919924381 : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-24 00:06:26,805 : INFO : stage_01_data_ingestion : >>>>> Stage Data ingestion stage started <<<<<<<]
[2024-02-24 00:06:26,809 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-24 00:06:26,813 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-24 00:06:26,813 : INFO : common : created directory at : artifacts]
[2024-02-24 00:06:26,815 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-24 00:06:26,816 : INFO : data_ingestion : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-24 00:10:35,148 : INFO : data_ingestion : Downloaded data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-24 00:10:46,104 : INFO : stage_01_data_ingestion : >>>>>> Stage Data ingestion stage completed <<<<<<

x===========x]
[2024-02-24 00:28:43,433 : INFO : stage_01_data_ingestion : >>>>> Stage Data ingestion stage started <<<<<<<]
[2024-02-24 00:28:43,435 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-24 00:28:43,436 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-24 00:28:43,437 : INFO : common : created directory at : artifacts]
[2024-02-24 00:28:43,437 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-24 00:28:43,437 : INFO : data_ingestion : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-24 00:32:54,950 : INFO : data_ingestion : Downloaded data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-24 00:33:02,608 : INFO : stage_01_data_ingestion : >>>>>> Stage Data ingestion stage completed <<<<<<

x===========x]
[2024-02-24 00:43:16,668 : INFO : stage_01_data_ingestion : >>>>> Stage Data ingestion stage started <<<<<<<]
[2024-02-24 00:43:16,671 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-24 00:43:16,672 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-24 00:43:16,672 : INFO : common : created directory at : artifacts]
[2024-02-24 00:43:16,672 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-24 00:43:16,673 : INFO : data_ingestion : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-24 00:47:35,119 : INFO : data_ingestion : Downloaded data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-24 00:47:44,007 : INFO : stage_01_data_ingestion : >>>>>> Stage Data ingestion stage completed <<<<<<

x===========x]
[2024-02-24 01:09:05,176 : INFO : stage_01_data_ingestion : >>>>> Stage Data ingestion stage started <<<<<<<]
[2024-02-24 01:09:05,178 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-24 01:09:05,179 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-24 01:09:05,180 : INFO : common : created directory at : artifacts]
[2024-02-24 01:09:05,180 : INFO : common : created directory at : artifcats/data_ingestion]
[2024-02-24 01:09:05,181 : INFO : data_ingestion : Downloading data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into artifacts/data_ingestion/data.zip folder]
[2024-02-24 01:13:12,785 : INFO : data_ingestion : Downloaded data from https://drive.google.com/file/d/1QQ-Fxrh3qmGSfbdlHSUQ0atLeoToHQLJ/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-24 01:13:20,521 : INFO : stage_01_data_ingestion : >>>>>> Stage Data ingestion stage completed <<<<<<

x===========x]
[2024-02-24 01:14:28,631 : INFO : stage_02_prepare_base_model : ******************]
[2024-02-24 01:14:28,631 : INFO : stage_02_prepare_base_model : >>>>>>>>> Stage Prepare Base Model started <<<<<<<<<<<]
[2024-02-24 01:14:28,633 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-24 01:14:28,634 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-24 01:14:28,635 : INFO : common : created directory at : artifacts]
[2024-02-24 01:14:28,635 : INFO : common : created directory at : artifacts/prepare_base_model]
[2024-02-24 01:14:29,093 : WARNING : saving_utils : Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-24 01:14:29,235 : INFO : stage_02_prepare_base_model : >>>>>>>>>> Stage Prepare Base Model completed <<<<<<<<<<<<

 x=============================x]
[2024-02-24 01:14:35,606 : INFO : stage_03_model_training : **********************]
[2024-02-24 01:14:35,606 : INFO : stage_03_model_training : >>>>>>>>>>>> Stage Training started <<<<<<<<<<<<<<<]
[2024-02-24 01:14:35,608 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-24 01:14:35,609 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-24 01:14:35,609 : INFO : common : created directory at : artifacts]
[2024-02-24 01:14:35,609 : INFO : common : created directory at : artifacts/training]
[2024-02-24 01:24:02,216 : INFO : stage_03_model_training : >>>>>>>>>>>>>>>> Stage Training completed <<<<<<<<<<<<<<<<

x=====================x]
[2024-02-24 01:24:12,326 : INFO : stage_04_model_evaluation_mlflow : ******************]
[2024-02-24 01:24:12,326 : INFO : stage_04_model_evaluation_mlflow : >>>>>>>>>>>>>>>>> Stage Evaluation Stage started <<<<<<<<<<<<<<<<<<<]
[2024-02-24 01:24:12,328 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-24 01:24:12,329 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-24 01:24:12,330 : INFO : common : created directory at : artifacts]
[2024-02-24 01:27:06,685 : INFO : common : json file saved at : scores.json]
[2024-02-24 01:27:06,686 : INFO : common : json file saved at : scores.json]
[2024-02-24 01:27:08,070 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-24 01:27:08,569 : INFO : builder_impl : Assets written to: C:\Users\Savi\AppData\Local\Temp\tmpar04d5mo\model\data\model\assets]
[2024-02-24 01:27:15,598 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\758d59c002844586aeffce9fc6f4a51d\artifacts\model\data]
[2024-02-24 01:27:15,599 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\758d59c002844586aeffce9fc6f4a51d\artifacts\model\data\model]
[2024-02-24 01:27:15,600 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\758d59c002844586aeffce9fc6f4a51d\artifacts\model\data\model\assets]
[2024-02-24 01:27:15,602 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\758d59c002844586aeffce9fc6f4a51d\artifacts\model\data\model\variables]
[2024-02-24 01:27:15,679 : INFO : stage_04_model_evaluation_mlflow : >>>>>>>>>>>>>> Stage Evaluation Stage completed <<<<<<<<<<<

x========================x]
[2024-02-24 02:23:41,451 : INFO : _internal : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.166:8080]
[2024-02-24 02:23:41,451 : INFO : _internal : [33mPress CTRL+C to quit[0m]
[2024-02-24 02:23:49,397 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 02:23:49] "GET / HTTP/1.1" 200 -]
[2024-02-24 02:25:03,108 : ERROR : app : Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 35, in predictRoute
    result = clApp.classifier.predict()
  File "c:\savi msi\complete data science\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\prediction.py", line 26, in predict
    prediction == 'Normal'
UnboundLocalError: local variable 'prediction' referenced before assignment
[2024-02-24 02:25:03,111 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 02:25:03] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-02-24 02:28:01,332 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 02:28:01] "GET / HTTP/1.1" 200 -]
[2024-02-24 02:28:08,887 : ERROR : app : Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 35, in predictRoute
    result = clApp.classifier.predict()
  File "c:\savi msi\complete data science\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\prediction.py", line 26, in predict
    prediction == 'Normal'
UnboundLocalError: local variable 'prediction' referenced before assignment
[2024-02-24 02:28:08,890 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 02:28:08] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-02-24 02:30:25,936 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 02:30:25] "GET / HTTP/1.1" 200 -]
[2024-02-24 02:30:34,324 : ERROR : app : Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 35, in predictRoute
    result = clApp.classifier.predict()
  File "c:\savi msi\complete data science\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\prediction.py", line 26, in predict
    prediction == 'Normal'
UnboundLocalError: local variable 'prediction' referenced before assignment
[2024-02-24 02:30:34,326 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 02:30:34] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-02-24 14:15:16,344 : INFO : _internal : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.166:8080]
[2024-02-24 14:15:16,346 : INFO : _internal : [33mPress CTRL+C to quit[0m]
[2024-02-24 14:15:27,580 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 14:15:27] "GET / HTTP/1.1" 200 -]
[2024-02-24 14:15:31,639 : ERROR : app : Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 35, in predictRoute
    result = clApp.classifier.predict()
  File "c:\savi msi\complete data science\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\prediction.py", line 15, in predict
    test_img = image.load_img(imagename, target_size=(224,224))
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\keras\utils\image_utils.py", line 423, in load_img
    img = pil_image.open(io.BytesIO(f.read()))
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\PIL\Image.py", line 3309, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x000001F6760544F0>
[2024-02-24 14:15:31,717 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 14:15:31] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-02-24 14:15:44,552 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 14:15:44] "GET / HTTP/1.1" 200 -]
[2024-02-24 14:15:57,801 : ERROR : app : Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 35, in predictRoute
    result = clApp.classifier.predict()
  File "c:\savi msi\complete data science\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\prediction.py", line 26, in predict
    prediction == 'Normal'
UnboundLocalError: local variable 'prediction' referenced before assignment
[2024-02-24 14:15:57,805 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 14:15:57] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-02-24 14:16:11,804 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 14:16:11] "GET / HTTP/1.1" 200 -]
[2024-02-24 14:16:32,143 : ERROR : app : Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 35, in predictRoute
    result = clApp.classifier.predict()
  File "c:\savi msi\complete data science\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\prediction.py", line 26, in predict
    prediction == 'Normal'
UnboundLocalError: local variable 'prediction' referenced before assignment
[2024-02-24 14:16:32,147 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 14:16:32] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-02-24 14:16:40,207 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 14:16:40] "GET / HTTP/1.1" 200 -]
[2024-02-24 14:16:51,069 : ERROR : app : Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 35, in predictRoute
    result = clApp.classifier.predict()
  File "c:\savi msi\complete data science\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\prediction.py", line 26, in predict
    prediction == 'Normal'
UnboundLocalError: local variable 'prediction' referenced before assignment
[2024-02-24 14:16:51,075 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 14:16:51] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-02-24 14:16:54,573 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 14:16:54] "GET / HTTP/1.1" 200 -]
[2024-02-24 14:19:55,319 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 14:19:55] "GET /train HTTP/1.1" 200 -]
[2024-02-24 14:19:55,405 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 14:19:55] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2024-02-24 14:20:23,904 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 14:20:23] "[31m[1mGET /predict HTTP/1.1[0m" 405 -]
[2024-02-24 14:20:43,686 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 14:20:43] "GET / HTTP/1.1" 200 -]
[2024-02-24 14:51:40,333 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 14:51:40] "GET / HTTP/1.1" 200 -]
[2024-02-24 14:51:49,230 : ERROR : app : Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 35, in predictRoute
    result = clApp.classifier.predict()
  File "c:\savi msi\complete data science\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\prediction.py", line 26, in predict
    prediction == 'Normal'
UnboundLocalError: local variable 'prediction' referenced before assignment
[2024-02-24 14:51:49,232 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 14:51:49] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-02-24 14:51:56,175 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 14:51:56] "GET / HTTP/1.1" 200 -]
[2024-02-24 14:53:27,386 : INFO : _internal : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.166:8080]
[2024-02-24 14:53:27,386 : INFO : _internal : [33mPress CTRL+C to quit[0m]
[2024-02-24 14:53:35,634 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 14:53:35] "GET / HTTP/1.1" 200 -]
[2024-02-24 14:53:49,752 : ERROR : app : Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Savi\.conda\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 35, in predictRoute
    result = clApp.classifier.predict()
  File "c:\savi msi\complete data science\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\prediction.py", line 26, in predict
    prediction == 'Normal'
UnboundLocalError: local variable 'prediction' referenced before assignment
[2024-02-24 14:53:49,755 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 14:53:49] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-02-24 14:58:05,568 : INFO : _internal : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.166:8080]
[2024-02-24 14:58:05,568 : INFO : _internal : [33mPress CTRL+C to quit[0m]
[2024-02-24 14:58:15,210 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 14:58:15] "GET / HTTP/1.1" 200 -]
[2024-02-24 14:58:25,494 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 14:58:25] "POST /predict HTTP/1.1" 200 -]
[2024-02-24 14:58:39,198 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 14:58:39] "POST /predict HTTP/1.1" 200 -]
[2024-02-24 14:58:46,496 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 14:58:46] "POST /predict HTTP/1.1" 200 -]
[2024-02-24 14:59:14,509 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 14:59:14] "POST /predict HTTP/1.1" 200 -]
[2024-02-24 14:59:25,134 : WARNING : polymorphic_function : 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x00000282E6F65310> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-02-24 14:59:25,140 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 14:59:25] "POST /predict HTTP/1.1" 200 -]
[2024-02-24 14:59:43,764 : WARNING : polymorphic_function : 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x00000282E6F65790> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-02-24 14:59:43,769 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 14:59:43] "POST /predict HTTP/1.1" 200 -]
[2024-02-24 15:03:56,465 : INFO : stage_03_model_training : **********************]
[2024-02-24 15:03:56,465 : INFO : stage_03_model_training : >>>>>>>>>>>> Stage Training started <<<<<<<<<<<<<<<]
[2024-02-24 15:03:56,471 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-24 15:03:56,473 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-24 15:03:56,473 : INFO : common : created directory at : artifacts]
[2024-02-24 15:03:56,474 : INFO : common : created directory at : artifacts/training]
[2024-02-24 16:06:00,307 : INFO : stage_03_model_training : >>>>>>>>>>>>>>>> Stage Training completed <<<<<<<<<<<<<<<<

x=====================x]
[2024-02-24 16:06:10,401 : INFO : stage_04_model_evaluation_mlflow : ******************]
[2024-02-24 16:06:10,401 : INFO : stage_04_model_evaluation_mlflow : >>>>>>>>>>>>>>>>> Stage Evaluation Stage started <<<<<<<<<<<<<<<<<<<]
[2024-02-24 16:06:10,403 : INFO : common : yaml file : config\config.yaml loaded successfully]
[2024-02-24 16:06:10,405 : INFO : common : yaml file : params.yaml loaded successfully]
[2024-02-24 16:06:10,405 : INFO : common : created directory at : artifacts]
[2024-02-24 16:07:58,075 : INFO : common : json file saved at : scores.json]
[2024-02-24 16:07:58,076 : INFO : common : json file saved at : scores.json]
[2024-02-24 16:07:59,057 : WARNING : save : Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-24 16:07:59,509 : INFO : builder_impl : Assets written to: C:\Users\Savi\AppData\Local\Temp\tmpqtytnt9d\model\data\model\assets]
[2024-02-24 16:08:06,033 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\b1f43f3432744497af89461958bba7e4\artifacts\model\data]
[2024-02-24 16:08:06,034 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\b1f43f3432744497af89461958bba7e4\artifacts\model\data\model]
[2024-02-24 16:08:06,035 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\b1f43f3432744497af89461958bba7e4\artifacts\model\data\model\assets]
[2024-02-24 16:08:06,038 : INFO : dir_util : creating C:\SAVI MSI\Complete Data Science\kidney-disease-classification-deep-learning-project\mlruns\0\b1f43f3432744497af89461958bba7e4\artifacts\model\data\model\variables]
[2024-02-24 16:08:06,125 : INFO : stage_04_model_evaluation_mlflow : >>>>>>>>>>>>>> Stage Evaluation Stage completed <<<<<<<<<<<

x========================x]
[2024-02-24 16:43:28,196 : INFO : _internal : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.166:8080]
[2024-02-24 16:43:28,201 : INFO : _internal : [33mPress CTRL+C to quit[0m]
[2024-02-24 16:43:30,992 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 16:43:30] "GET / HTTP/1.1" 200 -]
[2024-02-24 16:43:38,368 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 16:43:38] "POST /predict HTTP/1.1" 200 -]
[2024-02-24 16:43:48,946 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 16:43:48] "POST /predict HTTP/1.1" 200 -]
[2024-02-24 16:43:55,689 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 16:43:55] "POST /predict HTTP/1.1" 200 -]
[2024-02-24 16:44:02,491 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 16:44:02] "POST /predict HTTP/1.1" 200 -]
[2024-02-24 16:44:05,694 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 16:44:05] "GET / HTTP/1.1" 200 -]
[2024-02-24 16:44:11,925 : WARNING : polymorphic_function : 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000002769B855310> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-02-24 16:44:11,931 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 16:44:11] "POST /predict HTTP/1.1" 200 -]
[2024-02-24 16:45:07,563 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 16:45:07] "GET / HTTP/1.1" 200 -]
[2024-02-24 16:45:14,176 : WARNING : polymorphic_function : 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000002769B855790> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-02-24 16:45:14,180 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 16:45:14] "POST /predict HTTP/1.1" 200 -]
[2024-02-24 16:45:21,683 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 16:45:21] "POST /predict HTTP/1.1" 200 -]
[2024-02-24 16:45:28,309 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 16:45:28] "POST /predict HTTP/1.1" 200 -]
[2024-02-24 16:45:34,387 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 16:45:34] "POST /predict HTTP/1.1" 200 -]
[2024-02-24 16:45:40,001 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 16:45:40] "POST /predict HTTP/1.1" 200 -]
[2024-02-24 16:45:46,290 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 16:45:46] "POST /predict HTTP/1.1" 200 -]
[2024-02-24 16:45:52,982 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 16:45:52] "POST /predict HTTP/1.1" 200 -]
[2024-02-24 16:46:00,265 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 16:46:00] "POST /predict HTTP/1.1" 200 -]
[2024-02-24 16:46:07,114 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 16:46:07] "POST /predict HTTP/1.1" 200 -]
[2024-02-24 16:46:15,206 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 16:46:15] "POST /predict HTTP/1.1" 200 -]
[2024-02-24 16:46:22,123 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 16:46:22] "POST /predict HTTP/1.1" 200 -]
[2024-02-24 16:46:28,454 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 16:46:28] "POST /predict HTTP/1.1" 200 -]
[2024-02-24 16:46:33,169 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 16:46:33] "GET / HTTP/1.1" 200 -]
[2024-02-24 17:01:43,156 : INFO : _internal : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.166:8080]
[2024-02-24 17:01:43,156 : INFO : _internal : [33mPress CTRL+C to quit[0m]
[2024-02-24 17:01:45,748 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 17:01:45] "GET / HTTP/1.1" 200 -]
[2024-02-24 17:02:56,786 : INFO : _internal : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.166:8080]
[2024-02-24 17:02:56,786 : INFO : _internal : [33mPress CTRL+C to quit[0m]
[2024-02-24 17:02:59,444 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 17:02:59] "GET / HTTP/1.1" 200 -]
[2024-02-24 17:05:52,375 : INFO : _internal : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.166:8080]
[2024-02-24 17:05:52,375 : INFO : _internal : [33mPress CTRL+C to quit[0m]
[2024-02-24 17:05:55,122 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 17:05:55] "GET / HTTP/1.1" 200 -]
[2024-02-24 17:06:36,465 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 17:06:36] "POST /predict HTTP/1.1" 200 -]
[2024-02-24 17:06:58,201 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 17:06:58] "POST /predict HTTP/1.1" 200 -]
[2024-02-24 17:07:13,359 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 17:07:13] "POST /predict HTTP/1.1" 200 -]
[2024-02-24 17:07:27,073 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 17:07:27] "POST /predict HTTP/1.1" 200 -]
[2024-02-24 17:07:37,553 : WARNING : polymorphic_function : 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x00000267DB0E5310> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-02-24 17:07:37,561 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 17:07:37] "POST /predict HTTP/1.1" 200 -]
[2024-02-24 17:07:56,473 : WARNING : polymorphic_function : 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x00000267DB0E5790> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-02-24 17:07:56,478 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 17:07:56] "POST /predict HTTP/1.1" 200 -]
[2024-02-24 17:08:56,036 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 17:08:56] "POST /predict HTTP/1.1" 200 -]
[2024-02-24 17:12:13,852 : INFO : _internal : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.166:8080]
[2024-02-24 17:12:13,852 : INFO : _internal : [33mPress CTRL+C to quit[0m]
[2024-02-24 17:12:16,396 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 17:12:16] "GET / HTTP/1.1" 200 -]
[2024-02-24 17:12:27,982 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 17:12:27] "POST /predict HTTP/1.1" 200 -]
[2024-02-24 17:58:46,316 : INFO : _internal : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.166:8080]
[2024-02-24 17:58:46,317 : INFO : _internal : [33mPress CTRL+C to quit[0m]
[2024-02-24 17:58:51,215 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 17:58:51] "GET / HTTP/1.1" 200 -]
[2024-02-24 17:58:59,811 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 17:58:59] "POST /predict HTTP/1.1" 200 -]
[2024-02-24 18:06:05,744 : INFO : _internal : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.166:8080]
[2024-02-24 18:06:05,744 : INFO : _internal : [33mPress CTRL+C to quit[0m]
[2024-02-24 18:06:09,434 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 18:06:09] "GET / HTTP/1.1" 200 -]
[2024-02-24 18:06:18,355 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 18:06:18] "GET / HTTP/1.1" 200 -]
[2024-02-24 18:07:10,023 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 18:07:10] "POST /predict HTTP/1.1" 200 -]
[2024-02-24 18:07:33,391 : INFO : _internal : 127.0.0.1 - - [24/Feb/2024 18:07:33] "POST /predict HTTP/1.1" 200 -]
